# Generated by Django 3.2.7 on 2021-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
